### ISSUE TITLE
LSF to SLURM

### ISSUE THREAD

**Issue by pmb59** [ebi-gene-expression-group/atlas-bash-util#18]
We should aim to add
```
slurm.sh
atlas-slurm
```
with equivalent functionality as in
```
lsf.sh
atlas-lsf 
```
for the LSF scheduler. Probably `generic_routines.sh` will need some editing as well.

**Comment by anilthanki** [comment]
This is now fixed with merge of https://github.com/ebi-gene-expression-group/atlas-bash-util/pull/22, https://github.com/ebi-gene-expression-group/atlas-bash-util/pull/25, https://github.com/ebi-gene-expression-group/atlas-bash-util/pull/26, and https://github.com/ebi-gene-expression-group/atlas-bash-util/pull/27
